<?php
/**
 * Theme Functions
 * Generated by AI Theme Generator
 * Text Domain: {{ theme_slug }}
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Theme Setup
 */
function {{ theme_slug }}_setup() {
    // Add theme support
    {% for feature in features %}
    add_theme_support('{{ feature }}');
    {% endfor %}
    
    // Register navigation menus
    register_nav_menus(array(
        'primary' => __('Primary Menu', '{{ theme_slug }}'),
        'footer' => __('Footer Menu', '{{ theme_slug }}')
    ));
    
    // Add custom image sizes
    add_image_size('hero-banner', 1920, 1080, true);
    add_image_size('service-thumb', 400, 300, true);
    add_image_size('testimonial-avatar', 150, 150, true);
    
    // Add editor styles
    add_editor_style('assets/css/editor-style.css');
    
    // Enable HTML5 markup
    add_theme_support('html5', array(
        'search-form',
        'comment-form',
        'comment-list',
        'gallery',
        'caption'
    ));
}
add_action('after_setup_theme', '{{ theme_slug }}_setup');

/**
 * Enqueue Styles and Scripts
 */
function {{ theme_slug }}_scripts() {
    // Tailwind CSS
    wp_enqueue_style('tailwindcss', 'https://cdn.tailwindcss.com', array(), '3.3.0');
    
    // Theme styles
    wp_enqueue_style('{{ theme_slug }}-style', get_stylesheet_uri(), array('tailwindcss'), '1.0.0');
    
    // Custom CSS
    if (file_exists(get_template_directory() . '/assets/css/custom.css')) {
        wp_enqueue_style('{{ theme_slug }}-custom', get_template_directory_uri() . '/assets/css/custom.css', array(), '1.0.0');
    }
    
    // jQuery
    wp_enqueue_script('jquery');
    
    // Theme scripts
    wp_enqueue_script('{{ theme_slug }}-main', get_template_directory_uri() . '/assets/js/main.js', array('jquery'), '1.0.0', true);
    
    // Tailwind config
    $tailwind_config = '{{ tailwind_config | safe }}';
    wp_add_inline_script('tailwindcss', "tailwind.config = $tailwind_config;");
    
    // Localize script
    wp_localize_script('{{ theme_slug }}-main', '{{ theme_slug }}_ajax', array(
        'ajax_url' => admin_url('admin-ajax.php'),
        'nonce' => wp_create_nonce('{{ theme_slug }}_nonce'),
        'theme_name' => get_template()
    ));
}
add_action('wp_enqueue_scripts', '{{ theme_slug }}_scripts');

/**
 * Register Widget Areas
 */
function {{ theme_slug }}_widgets_init() {
    register_sidebar(array(
        'name' => __('Sidebar', '{{ theme_slug }}'),
        'id' => 'sidebar-1',
        'description' => __('Add widgets here.', '{{ theme_slug }}'),
        'before_widget' => '<section id="%1$s" class="widget %2$s bg-white rounded-lg shadow p-6 mb-6">',
        'after_widget' => '</section>',
        'before_title' => '<h3 class="widget-title text-xl font-bold text-gray-900 mb-4">',
        'after_title' => '</h3>',
    ));
    
    register_sidebar(array(
        'name' => __('Footer Widget Area 1', '{{ theme_slug }}'),
        'id' => 'footer-1',
        'description' => __('Footer widget area 1', '{{ theme_slug }}'),
        'before_widget' => '<div id="%1$s" class="widget %2$s">',
        'after_widget' => '</div>',
        'before_title' => '<h3 class="widget-title text-lg font-bold text-white mb-4">',
        'after_title' => '</h3>',
    ));
    
    register_sidebar(array(
        'name' => __('Footer Widget Area 2', '{{ theme_slug }}'),
        'id' => 'footer-2',
        'description' => __('Footer widget area 2', '{{ theme_slug }}'),
        'before_widget' => '<div id="%1$s" class="widget %2$s">',
        'after_widget' => '</div>',
        'before_title' => '<h3 class="widget-title text-lg font-bold text-white mb-4">',
        'after_title' => '</h3>',
    ));
    
    register_sidebar(array(
        'name' => __('Footer Widget Area 3', '{{ theme_slug }}'),
        'id' => 'footer-3',
        'description' => __('Footer widget area 3', '{{ theme_slug }}'),
        'before_widget' => '<div id="%1$s" class="widget %2$s">',
        'after_widget' => '</div>',
        'before_title' => '<h3 class="widget-title text-lg font-bold text-white mb-4">',
        'after_title' => '</h3>',
    ));
}
add_action('widgets_init', '{{ theme_slug }}_widgets_init');

{% if custom_post_types %}
/**
 * Register Custom Post Types
 */
function {{ theme_slug }}_custom_post_types() {
    {% for post_type in custom_post_types %}
    // {{ post_type|title }} Post Type
    register_post_type('{{ post_type }}', array(
        'labels' => array(
            'name' => __('{{ post_type|title }}s', '{{ theme_slug }}'),
            'singular_name' => __('{{ post_type|title }}', '{{ theme_slug }}'),
            'add_new' => __('Add New {{ post_type|title }}', '{{ theme_slug }}'),
            'add_new_item' => __('Add New {{ post_type|title }}', '{{ theme_slug }}'),
            'edit_item' => __('Edit {{ post_type|title }}', '{{ theme_slug }}'),
            'new_item' => __('New {{ post_type|title }}', '{{ theme_slug }}'),
            'view_item' => __('View {{ post_type|title }}', '{{ theme_slug }}'),
            'search_items' => __('Search {{ post_type|title }}s', '{{ theme_slug }}'),
            'not_found' => __('No {{ post_type }}s found', '{{ theme_slug }}'),
            'not_found_in_trash' => __('No {{ post_type }}s found in Trash', '{{ theme_slug }}')
        ),
        'public' => true,
        'has_archive' => true,
        'menu_icon' => 'dashicons-star-filled',
        'supports' => array('title', 'editor', 'thumbnail', 'excerpt'),
        'rewrite' => array('slug' => '{{ post_type }}'),
        'show_in_rest' => true
    ));
    {% endfor %}
}
add_action('init', '{{ theme_slug }}_custom_post_types');
{% endif %}

/**
 * Add Customizer Settings
 */
function {{ theme_slug }}_customize_register($wp_customize) {
    // Site Identity Section
    $wp_customize->add_section('{{ theme_slug }}_site_identity', array(
        'title' => __('Site Identity', '{{ theme_slug }}'),
        'priority' => 30,
    ));
    
    // Logo Upload
    $wp_customize->add_setting('{{ theme_slug }}_logo');
    $wp_customize->add_control(new WP_Customize_Image_Control($wp_customize, '{{ theme_slug }}_logo', array(
        'label' => __('Logo', '{{ theme_slug }}'),
        'section' => '{{ theme_slug }}_site_identity',
        'settings' => '{{ theme_slug }}_logo',
    )));
    
    // Colors Section
    $wp_customize->add_section('{{ theme_slug }}_colors', array(
        'title' => __('Theme Colors', '{{ theme_slug }}'),
        'priority' => 40,
    ));
    
    // Primary Color
    $wp_customize->add_setting('{{ theme_slug }}_primary_color', array(
        'default' => '#3b82f6',
        'sanitize_callback' => 'sanitize_hex_color',
    ));
    $wp_customize->add_control(new WP_Customize_Color_Control($wp_customize, '{{ theme_slug }}_primary_color', array(
        'label' => __('Primary Color', '{{ theme_slug }}'),
        'section' => '{{ theme_slug }}_colors',
        'settings' => '{{ theme_slug }}_primary_color',
    )));
    
    // Secondary Color
    $wp_customize->add_setting('{{ theme_slug }}_secondary_color', array(
        'default' => '#10b981',
        'sanitize_callback' => 'sanitize_hex_color',
    ));
    $wp_customize->add_control(new WP_Customize_Color_Control($wp_customize, '{{ theme_slug }}_secondary_color', array(
        'label' => __('Secondary Color', '{{ theme_slug }}'),
        'section' => '{{ theme_slug }}_colors',
        'settings' => '{{ theme_slug }}_secondary_color',
    )));
    
    // Hero Section
    $wp_customize->add_section('{{ theme_slug }}_hero', array(
        'title' => __('Hero Section', '{{ theme_slug }}'),
        'priority' => 50,
    ));
    
    // Hero Title
    $wp_customize->add_setting('{{ theme_slug }}_hero_title', array(
        'default' => __('Revolusi Digital untuk Bisnis Indonesia', '{{ theme_slug }}'),
        'sanitize_callback' => 'sanitize_text_field',
    ));
    $wp_customize->add_control('{{ theme_slug }}_hero_title', array(
        'label' => __('Hero Title', '{{ theme_slug }}'),
        'section' => '{{ theme_slug }}_hero',
        'type' => 'text',
    ));
    
    // Hero Subtitle
    $wp_customize->add_setting('{{ theme_slug }}_hero_subtitle', array(
        'default' => __('Transformasikan bisnis tradisional Indonesia menjadi powerhouse digital', '{{ theme_slug }}'),
        'sanitize_callback' => 'sanitize_textarea_field',
    ));
    $wp_customize->add_control('{{ theme_slug }}_hero_subtitle', array(
        'label' => __('Hero Subtitle', '{{ theme_slug }}'),
        'section' => '{{ theme_slug }}_hero',
        'type' => 'textarea',
    ));
    
    // Contact Information
    $wp_customize->add_section('{{ theme_slug }}_contact', array(
        'title' => __('Contact Information', '{{ theme_slug }}'),
        'priority' => 60,
    ));
    
    // Phone
    $wp_customize->add_setting('{{ theme_slug }}_phone');
    $wp_customize->add_control('{{ theme_slug }}_phone', array(
        'label' => __('Phone Number', '{{ theme_slug }}'),
        'section' => '{{ theme_slug }}_contact',
        'type' => 'text',
    ));
    
    // Email
    $wp_customize->add_setting('{{ theme_slug }}_email');
    $wp_customize->add_control('{{ theme_slug }}_email', array(
        'label' => __('Email Address', '{{ theme_slug }}'),
        'section' => '{{ theme_slug }}_contact',
        'type' => 'email',
    ));
    
    // Address
    $wp_customize->add_setting('{{ theme_slug }}_address');
    $wp_customize->add_control('{{ theme_slug }}_address', array(
        'label' => __('Address', '{{ theme_slug }}'),
        'section' => '{{ theme_slug }}_contact',
        'type' => 'textarea',
    ));
    
    // WhatsApp
    $wp_customize->add_setting('{{ theme_slug }}_whatsapp');
    $wp_customize->add_control('{{ theme_slug }}_whatsapp', array(
        'label' => __('WhatsApp Number', '{{ theme_slug }}'),
        'section' => '{{ theme_slug }}_contact',
        'type' => 'text',
        'description' => __('Include country code (e.g., +62)', '{{ theme_slug }}'),
    ));
}
add_action('customize_register', '{{ theme_slug }}_customize_register');

{% if contact_form %}
/**
 * Handle Contact Form Submission
 */
function {{ theme_slug }}_handle_contact_form() {
    // Verify nonce
    if (!wp_verify_nonce($_POST['{{ theme_slug }}_nonce'], '{{ theme_slug }}_contact_form')) {
        wp_die(__('Security check failed', '{{ theme_slug }}'));
    }
    
    // Sanitize input
    $name = sanitize_text_field($_POST['name']);
    $email = sanitize_email($_POST['email']);
    $phone = sanitize_text_field($_POST['phone']);
    $subject = sanitize_text_field($_POST['subject']);
    $message = sanitize_textarea_field($_POST['message']);
    
    // Validate required fields
    if (empty($name) || empty($email) || empty($message)) {
        wp_send_json_error(__('Please fill in all required fields', '{{ theme_slug }}'));
    }
    
    // Send email
    $to = get_option('admin_email');
    $subject = $subject ?: __('New Contact Form Submission', '{{ theme_slug }}');
    $body = sprintf(
        "Name: %s\nEmail: %s\nPhone: %s\n\nMessage:\n%s",
        $name,
        $email,
        $phone,
        $message
    );
    $headers = array('Content-Type: text/plain; charset=UTF-8');
    
    if (wp_mail($to, $subject, $body, $headers)) {
        wp_send_json_success(__('Thank you! Your message has been sent.', '{{ theme_slug }}'));
    } else {
        wp_send_json_error(__('Sorry, there was an error sending your message.', '{{ theme_slug }}'));
    }
}
add_action('wp_ajax_{{ theme_slug }}_contact_form', '{{ theme_slug }}_handle_contact_form');
add_action('wp_ajax_nopriv_{{ theme_slug }}_contact_form', '{{ theme_slug }}_handle_contact_form');
{% endif %}

/**
 * Add admin menu for theme options
 */
function {{ theme_slug }}_admin_menu() {
    add_theme_page(
        __('Theme Options', '{{ theme_slug }}'),
        __('Theme Options', '{{ theme_slug }}'),
        'edit_theme_options',
        '{{ theme_slug }}_options',
        '{{ theme_slug }}_options_page'
    );
}
add_action('admin_menu', '{{ theme_slug }}_admin_menu');

/**
 * Theme options page
 */
function {{ theme_slug }}_options_page() {
    ?>
    <div class="wrap">
        <h1><?php _e('Theme Options', '{{ theme_slug }}'); ?></h1>
        <div class="notice notice-info">
            <p><?php _e('This theme was generated by AI Theme Generator. Customize your site using the WordPress Customizer.', '{{ theme_slug }}'); ?></p>
        </div>
        
        <div class="card">
            <h2><?php _e('Theme Information', '{{ theme_slug }}'); ?></h2>
            <table class="form-table">
                <tr>
                    <th><?php _e('Theme Name:', '{{ theme_slug }}'); ?></th>
                    <td><?php echo get_template(); ?></td>
                </tr>
                <tr>
                    <th><?php _e('Version:', '{{ theme_slug }}'); ?></th>
                    <td>1.0.0</td>
                </tr>
                <tr>
                    <th><?php _e('Generator:', '{{ theme_slug }}'); ?></th>
                    <td>AI Theme Generator</td>
                </tr>
            </table>
        </div>
        
        <div class="card">
            <h2><?php _e('Quick Links', '{{ theme_slug }}'); ?></h2>
            <p>
                <a href="<?php echo admin_url('customize.php'); ?>" class="button button-primary">
                    <?php _e('Customize Theme', '{{ theme_slug }}'); ?>
                </a>
                <a href="<?php echo admin_url('nav-menus.php'); ?>" class="button">
                    <?php _e('Manage Menus', '{{ theme_slug }}'); ?>
                </a>
                <a href="<?php echo admin_url('widgets.php'); ?>" class="button">
                    <?php _e('Manage Widgets', '{{ theme_slug }}'); ?>
                </a>
            </p>
        </div>
    </div>
    <?php
}

/**
 * Add custom CSS to head
 */
function {{ theme_slug }}_custom_css() {
    $primary_color = get_theme_mod('{{ theme_slug }}_primary_color', '#3b82f6');
    $secondary_color = get_theme_mod('{{ theme_slug }}_secondary_color', '#10b981');
    
    ?>
    <style type="text/css">
        :root {
            --primary-color: <?php echo esc_attr($primary_color); ?>;
            --secondary-color: <?php echo esc_attr($secondary_color); ?>;
        }
        
        .gradient-bg {
            background: linear-gradient(135deg, <?php echo esc_attr($primary_color); ?> 0%, <?php echo esc_attr($secondary_color); ?> 100%) !important;
        }
        
        .gradient-text {
            background: linear-gradient(135deg, <?php echo esc_attr($primary_color); ?> 0%, <?php echo esc_attr($secondary_color); ?> 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
        }
    </style>
    <?php
}
add_action('wp_head', '{{ theme_slug }}_custom_css');

/**
 * Helper function to get theme option
 */
function {{ theme_slug }}_get_option($option, $default = '') {
    return get_theme_mod('{{ theme_slug }}_' . $option, $default);
}

/**
 * Custom excerpt length
 */
function {{ theme_slug }}_excerpt_length($length) {
    return 30;
}
add_filter('excerpt_length', '{{ theme_slug }}_excerpt_length');

/**
 * Custom excerpt more
 */
function {{ theme_slug }}_excerpt_more($more) {
    return '...';
}
add_filter('excerpt_more', '{{ theme_slug }}_excerpt_more');

/**
 * Add body classes
 */
function {{ theme_slug }}_body_classes($classes) {
    // Add page slug if available
    if (is_page()) {
        global $post;
        $classes[] = 'page-' . $post->post_name;
    }
    
    // Add custom classes based on page type
    if (is_front_page()) {
        $classes[] = 'front-page';
    }
    
    return $classes;
}
add_filter('body_class', '{{ theme_slug }}_body_classes');

/**
 * Enqueue block editor assets
 */
function {{ theme_slug }}_block_editor_assets() {
    wp_enqueue_style(
        '{{ theme_slug }}-block-editor',
        get_template_directory_uri() . '/assets/css/block-editor.css',
        array(),
        '1.0.0'
    );
}
add_action('enqueue_block_editor_assets', '{{ theme_slug }}_block_editor_assets');

/**
 * Load theme textdomain
 */
function {{ theme_slug }}_load_textdomain() {
    load_theme_textdomain('{{ theme_slug }}', get_template_directory() . '/languages');
}
add_action('after_setup_theme', '{{ theme_slug }}_load_textdomain');

/**
 * Remove WordPress version from head
 */
remove_action('wp_head', 'wp_generator');

/**
 * Security improvements
 */
// Remove WP version from RSS feeds
function {{ theme_slug }}_remove_wp_version_rss() {
    return '';
}
add_filter('the_generator', '{{ theme_slug }}_remove_wp_version_rss');

// Disable XML-RPC
add_filter('xmlrpc_enabled', '__return_false');

// Remove unnecessary header links
remove_action('wp_head', 'rsd_link');
remove_action('wp_head', 'wlwmanifest_link');

/**
 * Performance optimizations
 */
// Remove emoji scripts
remove_action('wp_head', 'print_emoji_detection_script', 7);
remove_action('wp_print_styles', 'print_emoji_styles');
remove_action('admin_print_scripts', 'print_emoji_detection_script');
remove_action('admin_print_styles', 'print_emoji_styles');

// Defer jQuery to footer
function {{ theme_slug }}_defer_jquery() {
    if (!is_admin()) {
        wp_deregister_script('jquery');
        wp_register_script('jquery', includes_url('/js/jquery/jquery.min.js'), false, NULL, true);
        wp_enqueue_script('jquery');
    }
}
add_action('wp_enqueue_scripts', '{{ theme_slug }}_defer_jquery', 1);

/**
 * Theme activation hook
 */
function {{ theme_slug }}_activation() {
    // Set default customizer values
    set_theme_mod('{{ theme_slug }}_primary_color', '#3b82f6');
    set_theme_mod('{{ theme_slug }}_secondary_color', '#10b981');
    
    // Flush rewrite rules
    flush_rewrite_rules();
}
add_action('after_switch_theme', '{{ theme_slug }}_activation');